name: auto generate data.js

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: node ./generateData.js
    - name: Check for Changes
      id: check_changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git diff --quiet || echo "diffChanges=true" >> $GITHUB_ENV
    - name: Commit and Push Changes
      if: env.diffChanges == 'true'
      run: |
        git add .
        git commit -m 'auto:generate data.js'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
